name: 'Delete old artifacts'
on:
  schedule:
    - cron: '50 16 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          expire-in: 7days # Setting this to 0 will delete all artifacts
